project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Bitter and Brined
    right:
      - href: WhoAte.qmd
      - href: WhatDidWeEat.qmd
    tools:
      - icon: github
        href: github.com
      
format:
  html:
    fontsize: 18px
    theme: [cosmo, styles.scss]

