---
title: What did we eat?
format:
  dashboard:
    orientation: rows
execute:
  echo: false
  warning: false
  error: false
  message: false
---

```{r}
library(tidyverse)

df = readxl::read_xlsx("data.xlsx", sheet = "Small")

df_long = df %>%
  pivot_longer(cols = Akshay:Morgan, 
               names_to = "Name", 
               values_to = "pctConsumed")
```

## Column 1 figures

```{r}
#| title: How did we eat it?

df %>%
  ggplot() +
  geom_bar(stat = "count", 
           aes(x = Category, fill = Category)) +
  labs(y = "Count",
       x = "") +
  theme_classic() +
  scale_fill_brewer(palette = "Dark2", guide = "none")
```

```{r}
#| title: Who ate how much of it?

df_long %>%
  ggplot() +
  geom_bar(stat = "identity",
           position = "fill",
           aes(x = Item, y = pctConsumed, fill = Name)) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_brewer(palette = "Dark2") +
  # geom_vline(xintercept = (1:14)+0.5) +
  coord_flip() +
  theme_classic() +
  labs(y = "Percent of Item Consumed (%)", x = "") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Column 2 - value boxes {width="35%"}

###

```{r}
most_items_eaten = df_long %>%
  filter(pctConsumed > 0) %>%
  count(Name)

max_eaten = max(most_items_eaten$n)

min_eaten = min(most_items_eaten$n)
```

::: {.valuebox icon="award-fill" color="#d4af37"}
Most Items Eaten:

`{r} max_eaten`

`{r} unique((most_items_eaten %>% filter(n == max_eaten))$Name)`
:::

::: {.valuebox icon="award-fill" color="#c0c0c0"}
Most silvers:

`{r} min_eaten`

`{r} unique((most_items_eaten %>% filter(n == min_eaten))$Name)`
:::

::: {.valuebox icon="award-fill" color="#cd7f32"}
Total Items:

`{r} length(unique(df$Item))`
:::



















